name: LawerensDrugs
version: '${project.version}'
main: xyz.lawerens.drugs.LawerensDrugs
api-version: '1.20'
commands:
  drugs:
    description: Comando principal de LawerensDrugs
    aliases: [drogas]